baseURL = "/"
languageCode = "en-us"
title = "Virginia Tech"
description = "A website for Virginia Tech's 2020 Data Science for the Public Good Program."
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$"]
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "UVA Biocomplexity Institute"
    description = "2020 DSPG VT Loudoun"
    logo = "favicon/uva-dspg-logo.jpg"
    githubUsername = "boya66"
    accent = "#232D4B" # dark colors do best
    backgroundColor = "#FFFFFF"
    font = "Oxygen" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "ascetic" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/overview/"
    name = "Overview"
    weight = 2

[[menu.main]]
    url = "/methods/"
    name = "Data & Methods"
    weight = 3

[[menu.main]]
    url = "/findings/"
    name = "Findings"
    weight = 4
    
[[menu.main]]
    url = "/team1/"
    name = "Team"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://biocomplexity.virginia.edu/social-decision-analytics/dspg-program"
    name = "fas fa-globe-americas"
    weight = 1

[[menu.icon]]
    url = "https://github.com/boya66/dspg2020Loudoun"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/UVA_BI"
    name = "fab fa-twitter"
    weight = 3
    
[[menu.icon]]
    url = "boya66@vt.edu"
    name = "far fa-envelope"
